### ISSUE TITLE
partsunlimited external source missing in Azure DW

### ISSUE THREAD

**Issue by radu-matei** [DxNext/2016-Oct-L2#3]
> Drag the 'logs' and the 'productcatalog' folder to the Storage explorer client and drop it into the 'partsunlimited' container.

You add the `productcatalog` into the `partsunlimited` container. 

Then, `AzureStorage` external data source is configured to look into the `processeddata` container.

```
CREATE EXTERNAL DATA SOURCE AzureStorage
WITH (
    TYPE = HADOOP,
    LOCATION = 'wasbs://processeddata@<Azure storage account name>.blob.core.windows.net',
    CREDENTIAL = AzureStorageCredential
);
```

Then, a bit later, the `AzureStorage` data source for `product_catalog` which is not present into the container.

```
CREATE EXTERNAL TABLE asb.ProductCatalogExternal
(
    SkuNumber nvarchar(50),
    Id int,
    ProductId nvarchar(20),     //is this supposed to be an int?
...
)
WITH (
    LOCATION='/product_catalog/',
    DATA_SOURCE=AzureStorage,
    FILE_FORMAT=TextFile
);
```

There should be another external source pointing to the `partsunlimited` container.

**Comment by romitgirdhar** [comment]
Issue fixed.

**Comment by romitgirdhar** [comment]
Issue fixed.
